require("prototypes.base")
require("prototypes.cannon_capsule")
require("prototypes.cannon_launcher")
require("prototypes.cannon_receiver")
require("prototypes.cannon_receiver_small")
require("prototypes.technology")
require("prototypes.style")
